#+title: Dotfiles
#+AUTHOR: Regalk

#+begin_export html
<div class="header">
  <ul class="topbar-menu-container">
    |
    <li class="topbar-menu current"><a href="index.html">Home</a></li>
    |
    <li class="topbar-menu"><a href="dotfiles.html">Dotfiles</a></li>
    |
    <li class="topbar-menu"><a target="_blank" href="https://github.com/regalk13/?tab=repositories">Projects</a></li>
    |
    <li class="topbar-menu"><a href="notes.html">Notes</a></li>
  </ul>
</div>
<br>
#+end_export

#+begin_export html
<p>These are my <span class="mark">dotfiles</span>. Dotfiles are configuration files for various command-line applications and utilities on <span class="mark">Unix-like</span> operating systems. They are called 'dotfiles' because their filenames begin with a dot (.) and are typically stored in the home directory. These files are loaded automatically when you start a new terminal session and contain customized settings for your shell, text editors, version control systems, and other command-line tools.

In my dotfiles, I have customized my <span class="mark">shell</span> prompts, <span class="mark">editors</span> and <span class="mark">Linux</span> tools.
Feel free to explore my dotfiles to see how I have customized my environment and workflow.</p>
#+end_export

* List of configurations

#+begin_export html
<ul id="dot-list">
    <li><a href="emacs.html">Emacs</a></li>
    <li>A</li>
</ul>

<script>
  const list = document.getElementById('dot-list');
  const items = Array.from(list.getElementsByTagName('li'));
  items.sort((a, b) => a.textContent.localeCompare(b.textContent));
  items.forEach(item => list.appendChild(item));
</script>
#+end_export
