#+title: Welcome to Regalk's place 

#+begin_export html
<div class="header">
  <ul class="topbar-menu-container">
    |
    <li class="topbar-menu current"><a href="#">Home</a></li>
    |
    <li class="topbar-menu"><a href="dotfiles.html">Dotfiles</a></li>
    |
    <li class="topbar-menu"><a target="_blank" href="https://github.com/regalk13/?tab=repositories">Projects</a></li>
    |
    <li class="topbar-menu"><a href="notes.html">Notes</a></li>
  </ul>
</div>
<br>
#+end_export

* About Me

#+begin_export html

<p>Current <span class="mark">Software Engineer</span>. Some years experience, specializing in the <span class="mark">backend development</span>, infrastructure automation, and computer graphics. Lover of editors and tools like <span class="mark">Emacs</span> and <span class="mark">Linux</span>. Interested in devising a better problem-solving methods for challenging tasks.</p>
<p>At the moment, this are the languages and frameworks that make up my stack: </p>
<ul>
   <li>C</li>
   <li>C++</li>
   <li>C#</li>
   <li>Rust</li>
   <li>Python</li>
   <li>JavaScript</li>
   <li>Java</li>
   <li>Nix</li>
   <li>SQL & NO-SQL</li>
</ul>


<p>Read more about my skills and projects in my <a href="https://github.com/regalk13">GitHub</a>.

<h3>Setup</h3>

<p>Linux Setup</p>
<p>- Distro: NixOs unstable or 24.11.</p>
<p>- Editor: Mostly emacs sometimes Vim.</p>
<p>- WM: Hyprland (Now a full-time Wayland user).</p>
<p>- Terminal: Kitty.</p>
<p>- Theme: Tokyo Night or Rosepine.</p>
<p>- Font: Iosevka NerdFont.</p>

<h3>Fun facts</h3>

<ul>
   <li>I'm a lifelong <span class="mark">learner</span>, always open to new knowlegde.</li>
   <li>I like to play Chess and GO.</li>
</ul>

#+end_export

* Notes

#+begin_export html
<p>Read my public notes at my <a href="notes.html">Notes Page</a></p>
#+end_export

* Contact me

#+begin_export html
<p>If you'd like to get in touch with me, feel free to reach out via Discord: <span class="mark">Regalk</span>. I'm always open to open source projects.</p>

#+end_export
