#+title: Welcome to Regalk's place 

#+begin_export html
<div class="header">
  <div class="topbar-menu-container">
    |
    <span class="topbar-menu current"><a href="#">Home</a></span>
    |
    <span class="topbar-menu"><a href="emacs.html">Dotfiles</a></span>
    |
    <span class="topbar-menu"><a href="#">Projects</a></span>
    |
    <span class="topbar-menu"><a href="#">Blog</a></span>
    |
  </div>
</div>
<br>
#+end_export

* About Me

#+begin_export html

<p>Current <span class="mark">Software Engineer</span>. Some years experience, specializing in the <span class="mark">backend development</span>, infrastructure automation, and computer graphics. Lover of editors and tools like <span class="mark">Emacs</span> and <span class="mark">Linux</span>. Interested in devising a better problem-solving methods for challenging tasks.</p>
<p>At the moment, this are the languages and frameworks that make up my stack: </p>
<ul>
   <li>C</li>
   <li>C++</li>
   <li>C#</li>
   <li>Rust</li>
   <li>Python</li>
   <li>JavaScript</li>
   <li>Java</li>
   <li>SQL & NO-SQL</li>
</ul>

<p>Read more about my skills and projects in my <a src="https://github.com/regalk13">github</a>.
<h3>Fun Facts</h3>

<ul>
   <li>I'm a lifelong <span class="mark">learner</span> who's always hungry for knowledge. Whether it's mastering a new programming language or exploring the latest trends in AI, I'm always up for a challenge.</li>
   <li>I really like to play <span class="mark">chess</span>. I love how the game challenges me to think ahead and strategize, and I'm always looking for new opponents to crush.</li>
   <li>I'm into DIY, in my free time I'm <span class="mark">fixing</span> everything I can and <span class="mark">building</span> what I need.</li>
   <li>I love the <span class="mark">computer graphics</span> field, programming, math and videogames in the same place!</li>
</ul>

#+end_export

* Contact me

#+begin_export html

<p>If you'd like to get in touch with me regarding a project, partnership, or other professional inquiry, feel free to reach out via email at <span class="mark">regalkinformation@gmail.com</span> or on Discord at <span class="mark">regalk#8443</span>. You can also find me on Twitter at <span class="mark">@reg4Ik</span>. I am always open to new opportunities and collaborations, and I strive to maintain clear and timely communication with all of my contacts.</p>
#+end_export
